package com.ian.community;

import org.junit.jupiter.api.Test;
import org.springframework.boot.env.YamlPropertySourceLoader;
import org.springframework.core.env.PropertySource;
import org.springframework.core.io.ClassPathResource;

import java.nio.charset.StandardCharsets;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

class AwsDeploymentConfigurationTest {

    @Test
    void awsProfileSupportsAAndBNetworkingWithSafeJpaSettings()
            throws Exception {
        List<PropertySource<?>> propertySources =
                new YamlPropertySourceLoader().load(
                        "application-aws",
                        new ClassPathResource(
                                "application-aws.yaml"
                        )
                );
        PropertySource<?> properties =
                propertySources.getFirst();

        assertThat(properties.getProperty("server.address"))
                .isEqualTo("${SERVER_ADDRESS:127.0.0.1}");
        assertThat(properties.getProperty(
                "spring.datasource.driver-class-name"
        )).isEqualTo("com.mysql.cj.jdbc.Driver");
        assertThat(properties.getProperty(
                "spring.jpa.hibernate.ddl-auto"
        )).isEqualTo("validate");
        assertThat(properties.getProperty(
                "spring.flyway.locations"
        )).isEqualTo("classpath:db/migration/mysql");
        assertThat(properties.getProperty(
                "spring.h2.console.enabled"
        )).isEqualTo(false);
        assertThat(properties.getProperty(
                "management.endpoints.web.exposure.include"
        )).isEqualTo("health");
        assertThat(properties.getProperty(
                "management.endpoint.health.show-details"
        )).isEqualTo("never");
    }

    @Test
    void mysqlMigrationIsSeparatedFromH2Syntax()
            throws Exception {
        ClassPathResource migration =
                new ClassPathResource(
                        "db/migration/mysql/"
                                + "V1__create_initial_schema.sql"
                );
        String sql = migration.getContentAsString(
                StandardCharsets.UTF_8
        );

        assertThat(sql)
                .contains(
                        "ENGINE=InnoDB",
                        "DEFAULT CHARSET=utf8mb4"
                )
                .doesNotContain(
                        "GENERATED BY DEFAULT AS IDENTITY",
                        "TIMESTAMP WITH TIME ZONE",
                        "seed_local_user"
                );
    }
}
