CREATE TABLE media_assets (
    media_id UUID PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    purpose VARCHAR(20) NOT NULL,
    status VARCHAR(30) NOT NULL,
    frame VARCHAR(30) NOT NULL,
    rotation INT NOT NULL,
    crop_x DECIMAL(12, 9) NOT NULL,
    crop_y DECIMAL(12, 9) NOT NULL,
    crop_width DECIMAL(12, 9) NOT NULL,
    crop_height DECIMAL(12, 9) NOT NULL,
    source_key VARCHAR(500) NOT NULL UNIQUE,
    master_key VARCHAR(500),
    declared_content_type VARCHAR(50) NOT NULL,
    declared_file_size BIGINT NOT NULL,
    source_width INT,
    source_height INT,
    active_revision INT NOT NULL,
    latest_revision INT NOT NULL,
    transform_version INT NOT NULL,
    error_code VARCHAR(80),
    lease_until TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    deleted_at TIMESTAMP(6),
    record_version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_media_assets_owner FOREIGN KEY (owner_user_id) REFERENCES users (user_id)
);

CREATE INDEX idx_media_assets_owner_status ON media_assets(owner_user_id, status);
CREATE INDEX idx_media_assets_status_lease ON media_assets(status, lease_until);

CREATE TABLE media_revisions (
    media_revision_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    media_id UUID NOT NULL,
    revision INT NOT NULL,
    status VARCHAR(30) NOT NULL,
    frame VARCHAR(30) NOT NULL,
    rotation INT NOT NULL,
    crop_x DECIMAL(12, 9) NOT NULL,
    crop_y DECIMAL(12, 9) NOT NULL,
    crop_width DECIMAL(12, 9) NOT NULL,
    crop_height DECIMAL(12, 9) NOT NULL,
    zoom DECIMAL(6, 3) NOT NULL,
    position_x DECIMAL(12, 9) NOT NULL,
    position_y DECIMAL(12, 9) NOT NULL,
    transform_version INT NOT NULL,
    error_code VARCHAR(80),
    lease_until TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    activated_at TIMESTAMP(6),
    deleted_at TIMESTAMP(6),
    record_version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_media_revisions_asset FOREIGN KEY (media_id) REFERENCES media_assets (media_id),
    CONSTRAINT uk_media_revisions_asset_revision UNIQUE (media_id, revision)
);

CREATE INDEX idx_media_revisions_status_lease
    ON media_revisions(status, lease_until);

CREATE TABLE media_variants (
    media_variant_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    media_id UUID NOT NULL,
    variant_type VARCHAR(40) NOT NULL,
    object_key VARCHAR(500) NOT NULL,
    width INT NOT NULL,
    height INT NOT NULL,
    mime_type VARCHAR(50) NOT NULL,
    file_size BIGINT NOT NULL,
    media_revision INT NOT NULL,
    transform_version INT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_media_variants_asset FOREIGN KEY (media_id) REFERENCES media_assets (media_id),
    CONSTRAINT uk_media_variants_asset_type_revision_transform
        UNIQUE (media_id, variant_type, media_revision, transform_version)
);

ALTER TABLE users ALTER COLUMN profile_image VARCHAR(500);
ALTER TABLE users ADD COLUMN profile_media_id UUID;
ALTER TABLE users ADD CONSTRAINT fk_users_profile_media
    FOREIGN KEY (profile_media_id) REFERENCES media_assets (media_id);

ALTER TABLE post_images DROP CONSTRAINT IF EXISTS uk_post_images_post;
ALTER TABLE post_images ALTER COLUMN image_url VARCHAR(500);
ALTER TABLE post_images ADD COLUMN media_id UUID;
ALTER TABLE post_images ADD COLUMN display_order INT DEFAULT 0 NOT NULL;
ALTER TABLE post_images ADD CONSTRAINT fk_post_images_media
    FOREIGN KEY (media_id) REFERENCES media_assets (media_id);
ALTER TABLE post_images ADD CONSTRAINT uk_post_images_post_order
    UNIQUE (post_id, display_order);
